language: ruby
cache: bundler

rvm:
- 2.3.7
- 2.4.4
- 2.5.3

before_install:
  - sudo apt-get update
  - sudo apt-get install python
  - nvm install node
  - nvm use node
  - gem install bundler:1.16.3

install:
  - pip install --user bumpversion
  - npm install -g semantic-release
  - npm install -g @semantic-release/exec
  - npm install -g @semantic-release/git
  - bundle _1.16.3_ install

script:
  - bundle exec rake

deploy:
  - provider: script
    script: npx semantic-release
    on:
      branch: master
      rvm: 2.5.3

  - provider: rubygems
    api_key: $RUBYGEMS_API_KEY
    gem: ibm_cloud_sdk_core
    on:
      branch: master
      rvm: 2.5.3

matrix:
  fast_finish: true

notifications:
  email: false
